version: '3.8'

services:
  app:
    build: app/
    container_name: app
    environment:
      - FLASK_ENV=development
    volumes:
      - ./logs/app:/srv/logs
      - ./app:/usr/src/app

  auth:
    build: auth/
    container_name: auth
    environment:
      - FLASK_ENV=development
      - FLASK_SECRET_KEY=notsosecret
    volumes:
      - ./logs/auth:/srv/logs
      - ./auth:/usr/src/app

  server:
    image: nginx:latest
    container_name: server
    depends_on:
      - app
      - auth
    ports:
      - 9999:80
    volumes:
      - ./server/conf.d/:/etc/nginx/conf.d
      - ./logs/server:/var/log/nginx
