version: '3.8'

services:
  app:
    build: app/  
    container_name: app
    volumes:
      - ./logs/app:/srv/logs

  auth:
    build: auth/  
    container_name: auth
    volumes:
      - ./logs/auth:/srv/logs

  server:
    image: nginx:latest
    container_name: server
    depends_on:
      - app
      - auth
    ports:
      - 80:80
    volumes:
      - ./server/conf.d/:/etc/nginx/conf.d
      - ./logs/server:/var/log/nginx
